desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/smarttachitoshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static #agregar ruta estatica a url paters(rutas de la apliacion)
#ruta estatica son las imagenes 

urlpatterns = [
    path("", include("web.urls")), #path principal referenciado a urls de la aplicacion
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #agregar ruta estatica a url paters(rutas de la apliacion)

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/urls.py
from django.urls import path

from . import views  #from . significa que importame el archivo views

app_name = 'web' #esto para ubicar los enlaces, indicarle en que apliacion esta

#urlpatters es la lista de las rutas
urlpatterns = [
    path('', views.index,name='index'), #significa que cuando se entre a la raiz de la pagina, se ejecute la funcion index
    path ('productosPorCategoria/<int:categoria_id>/',views.productosPorCategoria,name='productosPorCategoria'),
    path ('productosPorNombre/',views.productosPorNombre,name='productosPorNombre')
] 

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True) #autonow indica que se coloca la fecha automaticamente

   #este metodo ayuda cuando instancio un objeto de la clase categoria por defecto me devuelva el nombre
    def __str__(self) -> str:
        return self.nombre
    
class Producto(models.Model):
    #El foreingKey(clave foranea) se usa para relacionar una tabla con otra la relacion es de una a muchos
    #on_delete=models.RESTRICT cuando alguien borre categoria no le permita si tiene productos creados(Integridad referencial)
    categoria=models.ForeignKey(Categoria, on_delete=models.RESTRICT) # () significa hacia la clase categoria
    nombre=models.CharField(max_length=200) #Un campo charfield tiene 255 caract equivalente a varchar(255)
    #por defecto me permita nulos porque no pueden tener descripcion
    descripcion=models.TextField(null=True) #Un campo textfield es equivalente a un campo text en mysql + de 255 caracte
    precio = models.DecimalField(max_digits=9, decimal_places=2) #Un campo decimal es equivalente a un campo decimal en mysql
    fecha_registro = models.DateTimeField(auto_now_add=True) #autonow indica que se coloca la fecha automaticamente
    imagen = models.ImageField(upload_to='productos', blank=True) #Un campo imagefield es equivalente a un campo blob en mysql
    
    def __str__(self) -> str:
        return self.nombre

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/views.py
from django.shortcuts import render

from .models import Categoria,Producto
# Create your views here.
"""VISTAS PARA EL CATALOGO DE PRODUCTOS"""
 

def index(request): # Vista para la pagina principal
    listaCategorias = Categoria.objects.all() # Obtener todas las categorias de la base de datos
    listaProductos = Producto.objects.all() # Obtener todos los productos de la base de datos
   # listaCategorias = Categoria.objets.all()
    # Crear un diccionario con los productos porque la plantilla espera un diccionario  
   
    context={
        'productos':listaProductos, #enviando un diccionario con primarea clave productos cuyo valor tiene un listado que vien dela DB
        'categorias':listaCategorias #enviando un diccionario con primarea clave categorias cuyo valor tiene un listado que vien dela DB
    }
    return render(request, 'index.html',context)    # Mostrar para comprobar las plantillas

def productosPorCategoria(request,categoria_id):
    """ vista para filtrar productos por categoria """
    objCategoria = Categoria.objects.get(pk=categoria_id) # Obtener la categoria por su id
    listaProductos = objCategoria.producto_set.all() # Obtener listado productos de la categoria

    listaCategorias = Categoria.objects.all() # Obtener todas las categorias de la base de datos

    context={  
        'productos':listaProductos, #enviando un diccionario con primarea clave productos cuyo valor tiene un listado que vien dela DB
        'categorias':listaCategorias #enviando un diccionario con primarea clave categorias cuyo valor tiene un listado que vien dela DB
    }

    return render(request, 'index.html',context)    # Mostrar para comprobar las plantillas

def productosPorNombre(request):
    #vendra de un formulario
    """ vista para filtrar productos por nombre """
    nombre = request.POST['nombre'] # Obtener el nombre del producto a buscar capturo
    listaProductos = Producto.objects.filter(nombre__contains=nombre) # Me trae todos los productos que contengan el nombre
    
    listaCategorias = Categoria.objects.all() # Obtener todas las categorias de la base de datos

    context={  
        'productos':listaProductos, #enviando un diccionario con primarea clave productos cuyo valor tiene un listado que vien dela DB
        'categorias':listaCategorias #enviando un diccionario con primarea clave categorias cuyo valor tiene un listado que vien dela DB
    }

    return render(request, 'index.html',context)    # Mostrar para comprobar las plantillas

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="product.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.categoria}}</a>
                        </p>
                        <h3><a href="product.html">{{ value.nombre }}</a></h3>
                    </div><!--
    No Space
    --><div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Precio</p>
                        <p class="prod-li-price">${{value.precio}}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{value.cantidad}}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!--
No Space
--></div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/cuenta.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.first_name }} {{ user.last_name }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente|crispy }}
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>COMPRA</li>
    </ul>
    <h2>GRACIAS POR TU COMPRA</h2>    
{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/catalogo/catalogo.html
<div class="row prod-items prod-items-2">
    {% for producto in productos %}  <!-- Recorremos los productos de la lista -->
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="#">
                    {% if producto.imagen %}
                    <img src="{{producto.imagen.url}}" alt="">&nbsp;
                    {% else %}
                        <img src="https://via.placeholder.com/250" alt="">
                    {% endif %}
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <p class="prod-i-cart">
                            <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Añadir al carrito</span></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{producto.precio}}</p>
                    <p class="prod-i-categ"><a href="#"></a>{{producto.categoria}}</p>
                </div>
                <h3 class="prod-i-ttl"><a href="#">{{producto.nombre}}</a></h3>
            </div>
        </div>
    </article>
    <!--almacenamos lo que viene del diccionario dentro una variable llamada producto-->
    {% endfor %}
</div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">
    <h3 class="widgettitle">Categorias</h3>
    <div class="section-sb-current">
        <ul class="section-sb-list">
            {% for categoria in categorias %}
            <li>
                <a href="{% url 'web:productosPorCategoria' categoria.id %}">
                    <span class="section-sb-label">{{categoria.nombre}}
                        <span class="count">{{categoria.producto_set.all.cout}}</span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/footer.html
{% load static %}
<!--footer-->
    <div class="container-fluid blog-sb-widgets page-styling site-footer">
        <div class="row">
            <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
                <a href="index.html" class="f-logo">
                    <img src="{% static 'img/logo2.png' %}" alt="">
                </a>
                <p>Proyecto Ecommerce con Django para Desconfigurados</p>
                <button class="btn callback">Contacto</button>
            </div>
        </div>
    </div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/header.html
{% load static %}
    <!--header-->
    <div class="site-header">

        <p class="h-logo">
            <a href="/"><img src="{% static 'img/logo2.png' %}" alt="EdShop"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="post" action="{% url 'web:productosPorNombre' %}" class="h-search" id="h-search">
            {% csrf_token %}
            <input type="text" name="nombre" placeholder="Buscar...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

        <ul class="h-shop-links">
            <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
            
            <li class="h-shop-icon h-profile">
                <a href="auth.html" title="My Account">
                    <i class="ion-android-person"></i>
                </a>
                <ul class="h-profile-links">
                    <li><a href="/login">Login / Registro</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>

            {% include 'includes/header_carrito.html' %}


        </ul>
    </div></div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/header_carrito.html
<li class="h-cart">
    <a class="cart-contents" href="cart.html">
        <p class="h-cart-icon">
            <i class="ion-android-cart"></i>
            <span>1</span>
        </p>
        <p class="h-cart-total">$100</p>
    </a>
    <div class="widget_shopping_cart">
        <div class="widget_shopping_cart_content">
            <ul class="cart_list">
                
                <li>
                    <a href="#" class="remove">&times;</a>
                    <a href="#">
                        <img src="https://via.placeholder.com/250" alt="">
                        Producto
                    </a>
                    <span class="quantity">1 &times; $100</span>
                </li>
                
            </ul>
            <p class="total"><b>Subtotal:</b> $100</p>
            <p class="buttons">
                <a href="#" class="button">Ver Carrito</a>
                <a href="#" class="button">Pedido</a>
            </p>
        </div>
    </div>
</li>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/navbar.html
<!--navbar-->
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Dirección
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle 123,Lima Perú</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contacto
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Telefono
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">(478)-592-9899</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/includes/relacionados.html
<h2 class="prod-related-ttl">Related Products</h2>
    <div class="row prod-items prod-items-4">
        <article class="cf-sm-6 cf-md-6 cf-lg-3 col-xs-6 col-sm-6 col-md-6 col-lg-3 sectgl-item sectgl-item">
            <div class="sectgl prod-i">
                <div class="prod-i-top">
                    <a class="prod-i-img" href="product.html">
                        <img src="http://placehold.it/290x258" alt="">
                    </a>
                    <div class="prod-i-actions">
                        <div class="prod-i-actions-in">
                            <div class="prod-li-favorites">
                                <a href="wishlist.html" class="hover-label add_to_wishlist"><i class="icon ion-heart"></i><span>Add to Wishlist</span></a>
                            </div>
                            <p class="prod-quickview">
                                <a href="#" class="hover-label quick-view"><i class="icon ion-plus"></i><span>Quick View</span></a>
                            </p>
                            <p class="prod-i-cart">
                                <a href="#" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Add to Cart</span></a>
                            </p>
                            <p class="prod-li-compare">
                                <a href="compare.html" class="hover-label prod-li-compare-btn"><span>Compare</span><i class="icon ion-arrow-swap"></i></a>
                            </p>
                        </div>
                    </div>
                    <p class="prod-i-badge"><span>Sale</span></p>
                </div>
                <div class="prod-i-bot">
                    <div class="prod-i-info">
                        <p class="prod-i-price">$70.00</p>
                        <p class="prod-i-categ"><a href="catalog-gallery.html">Electricity</a></p>
                    </div>
                    <h3 class="prod-i-ttl"><a href="product.html">Universal Plug</a></h3>
                </div>
            </div>
        </article>
    </div>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
        <div class="section-top">

            <h1 class="maincont-ttl">Catalogo</h1>
            <ul class="b-crumbs">
                <li><a href="/">Inicio</a></li>
                <li>Catalogo</li>
            </ul>
        </div>
        <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
        <div class="section-wrap-withsb">
            <aside class="blog-sb-widgets section-sb" id="section-sb">
                <div class="theiaStickySidebar">
                    <p class="section-filter-toggle filter_hidden">
                        <a href="#" id="section-filter-toggle-btn">Filtros</a>
                    </p>
                    <div class="section-filter">
                        <div class="section-filter">
                            {% include 'includes/catalogo/categorias.html' %}
                        </div>
                    </div>
                </div>
            </aside>        <div class="section-list-withsb" id="section-list-withsb">
            <div class="theiaStickySidebar">
                {% include 'includes/catalogo/catalogo.html' %}
            </div><!-- .theiaStickySidebar -->
        </div><!-- .section-list-withsb -->
        </div><!-- .section-wrap-withsb -->
{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SmarttachitoShop</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">

    {% include 'includes/navbar.html' %}

    {% include 'includes/header.html' %}

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

    {% include 'includes/footer.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>                                                <article class="page-cont">
    <div class="page-styling">


        <div class="auth-wrap">
            <div class="auth-col">
                <h2>Login</h2>
                <form method="post" class="login" action="{% url 'web:loginUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="username">E-mail <span class="required">*</span></label>
                        <input type="text" id="username" name="usuario">
                    </p>
                    <p>
                        <label for="password">Password <span class="required">*</span></label>
                        <input type="password" id="password" name="password">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Login">
                        <input type="checkbox" id="rememberme" value="forever">
                        <label for="rememberme">Remember me</label>
                    </p>
                    <p>
                        <label for="alert-danger"> {{error}}</label>
                    </p>
                    <p class="auth-lost_password">
                        <a href="#">Lost your password?</a>
                    </p>
                </form>
            </div>
            <div class="auth-col">
                <h2>Registro</h2>
                <form method="post" class="register" action="{% url 'web:crearUsuario' %}">
                    {% csrf_token %}
                    <p>
                        <label for="reg_email">Email <span class="required">*</span></label>
                        <input type="email" id="reg_email" name="nuevoUsuario">
                    </p>
                    <p>
                        <label for="reg_password">Password <span class="required">*</span></label>
                        <input type="password" id="reg_password" name="nuevoPassword">
                    </p>
                    <p class="auth-submit">
                        <input type="submit" value="Crear Cuenta">
                    </p>
                </form>
            </div>
        </div>


    </div>
</article>

{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/pedido.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NRO : {{pedido.nro_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {% for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{ detalle.producto.imagen.url }}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="product.html">{{ detalle.producto.nombre }}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{ formpaypal.render }}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

desarrollo/smarttachito/fuentes/frontend/workspace/smarttachitoshop/web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}